#! /bin/sh
# /etc/init.d/light_control_starter

# You need to register your script to run at boot
# sudo update-rc.d light_control_starter defaults

# To remove it from boot:
# sudo update-rc.d -f light_control_starter remove

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting light_control.py"
    (sleep 20;/mnt/code/raspberry_adc/light_control.py --log /mnt/code/log/light_control.log)&
    ;;
  stop)
    echo "Stopping light_control.py"
    sudo killall -9 light_control.py
    ;;
  restart)
    echo "Stopping light_control.py"
    sudo killall -9 light_control.py
    echo "Starting light_control.py"
    sudo /mnt/code/raspberry_adc/light_control.py --log /mnt/code/log/light_control.log &
    ;;
  *)
    echo "Usage: /etc/init.d/light_control_starter {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
